name: Build and Deploy
on:
  push:
    branches: 
      - main
jobs:
  build: 
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@main
  
      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '18.12.1'
      
      - name: Install and Build
        run: |
          npm ci
          npm run build 
      
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          
